### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Mhasanpour** [andreili/STM32F4#1]
Hello friend 
I am new to this issue. I want to make a PLC using the STM32F103 chip working with IEC 61131. Could please let us know how can I use your code?

**Comment by andreili** [comment]
Hi.
Please, see the configuration file: https://github.com/andreili/STM32FX_FM/blob/master/Examples/STM32VLDISCOVERY/inc/stm32_conf.h#L80
All initialization parameters (PLL, etc.) are hardcoded to compile-time for a minimize the binary file size and more perfomances.
But, this code unsupported by me, sorry :(
